name: eshop
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.2 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/eshop/assets/images/prison.svg
    - packages/eshop/assets/images/colordropper.svg
    - packages/eshop/assets/images/textcolor.svg
    - packages/eshop/assets/images/design.svg
    - packages/eshop/assets/images/foursquares.svg
    - packages/eshop/assets/images/edit.svg
    - packages/eshop/assets/images/8.svg
    - packages/eshop/assets/images/10.svg
    - packages/eshop/assets/images/vector.svg
    - packages/eshop/assets/images/image20.png
    - packages/eshop/assets/images/line23.svg
    - packages/eshop/assets/images/11.svg
    - packages/eshop/assets/images/image21.png
    - packages/eshop/assets/images/line24.svg
    - packages/eshop/assets/images/image22.png
    - packages/eshop/assets/images/line25.svg
    - packages/eshop/assets/images/rectangle344.png
    - packages/eshop/assets/images/line16.svg
    - packages/eshop/assets/images/line17.svg
    - packages/eshop/assets/images/rectangle316.svg
    - packages/eshop/assets/images/ellipse35.png
    - packages/eshop/assets/images/forward.svg
    - packages/eshop/assets/images/ellipse61.png
    - packages/eshop/assets/images/ellipse62.png
    - packages/eshop/assets/images/vector22.svg
    - packages/eshop/assets/images/vector23.svg
    - packages/eshop/assets/images/ellipse65.png
    - packages/eshop/assets/images/ellipse66stroke.svg
    - packages/eshop/assets/images/vector24.svg
    - packages/eshop/assets/images/vector25.svg
    - packages/eshop/assets/images/image16.png
    - packages/eshop/assets/images/image17.png
    - packages/eshop/assets/images/image18.png
    - packages/eshop/assets/images/ellipse36.png
    - packages/eshop/assets/images/line7.svg
    - packages/eshop/assets/images/rectangle101.svg
    - packages/eshop/assets/images/image15.png
    - packages/eshop/assets/images/rectangle429.png
    - packages/eshop/assets/images/rectangle430.png
    - packages/eshop/assets/images/rectangle431.png
    - packages/eshop/assets/images/rectangle432.png
    - packages/eshop/assets/images/line18.svg
    - packages/eshop/assets/images/ellipse67.png
    - packages/eshop/assets/images/360view.svg
    - packages/eshop/assets/images/ellipse37.png
    - packages/eshop/assets/images/3.svg
    - packages/eshop/assets/images/mastercard.svg
    - packages/eshop/assets/images/line19.svg
    - packages/eshop/assets/images/line20.svg
    - packages/eshop/assets/images/line21.svg
    - packages/eshop/assets/images/vector5.svg
    - packages/eshop/assets/images/ellipse69.png
    - packages/eshop/assets/images/ellipse68.png
    - packages/eshop/assets/images/line22.svg
    - packages/eshop/assets/images/5.svg
    - packages/eshop/assets/images/happy.svg
    - packages/eshop/assets/images/inlove.svg
    - packages/eshop/assets/images/disappointed.svg
    - packages/eshop/assets/images/vector4.svg
    - packages/eshop/assets/images/fullscreenblacksmartphonemockupdesign51.png
    - packages/eshop/assets/images/101.png
    - packages/eshop/assets/images/group.svg
    - packages/eshop/assets/images/rectangle325.png
    - packages/eshop/assets/images/vector7.svg
    - packages/eshop/assets/images/vector10.svg
    - packages/eshop/assets/images/vector9.svg
    - packages/eshop/assets/images/rectangle319.svg
    - packages/eshop/assets/images/union.svg
    - packages/eshop/assets/images/twitter.svg
    - packages/eshop/assets/images/instagram.svg
    - packages/eshop/assets/images/youtube.svg
    - packages/eshop/assets/images/star1.svg
    - packages/eshop/assets/images/plus.svg
    - packages/eshop/assets/images/back.svg
    - packages/eshop/assets/images/vector2.svg
    - packages/eshop/assets/images/vector15.svg
    - packages/eshop/assets/images/vector16.svg
    - packages/eshop/assets/images/vector17stroke.svg
    - packages/eshop/assets/images/subtract.png
    - packages/eshop/assets/images/vector18.svg
    - packages/eshop/assets/images/vector19.svg
    - packages/eshop/assets/images/vector20.svg
    - packages/eshop/assets/images/vector21.svg
    - packages/eshop/assets/images/ellipse64.png
    - packages/eshop/assets/images/arrow.svg
    - packages/eshop/assets/images/call.svg
    - packages/eshop/assets/images/ellipse33.svg
    - packages/eshop/assets/images/ellipse22.png
    - packages/eshop/assets/images/componentsiconfilter.svg
    - packages/eshop/assets/images/vector8.svg
    - packages/eshop/assets/images/vector115.svg
    - packages/eshop/assets/images/vector116.svg
    - packages/eshop/assets/images/downloadfromcloud.svg
    - packages/eshop/assets/images/rectangle333.png
    - packages/eshop/assets/images/rectangle332.png
    - packages/eshop/assets/images/rectangle334.png
    - packages/eshop/assets/images/rectangle335.png
    - packages/eshop/assets/images/miroodlessticker.png
    - packages/eshop/assets/images/no_name_1.svg
    - packages/eshop/assets/images/rectangle321.png
    - packages/eshop/assets/images/9.svg
    - packages/eshop/assets/images/image12.png
    - packages/eshop/assets/images/ellipse4.png
    - packages/eshop/assets/images/polygon1.svg
    - packages/eshop/assets/images/image9.png
    - packages/eshop/assets/images/devider.svg
    - packages/eshop/assets/images/tiffanyco.svg
    - packages/eshop/assets/images/gucci.svg
    - packages/eshop/assets/images/catier.svg
    - packages/eshop/assets/images/boss.svg
    - packages/eshop/assets/images/burberry.svg
    - packages/eshop/assets/images/prada.svg
    - packages/eshop/assets/images/ellipse3.png
    - packages/eshop/assets/images/image10.png
    - packages/eshop/assets/images/line13.svg
    - packages/eshop/assets/images/line12.svg
    - packages/eshop/assets/images/divider.svg
    - packages/eshop/assets/images/line15.svg
    - packages/eshop/assets/images/ellipse34.png
    - packages/eshop/assets/images/shape.png
    - packages/eshop/assets/images/path.svg
    - packages/eshop/assets/images/donotbleach.svg
    - packages/eshop/assets/images/donotwash.svg
    - packages/eshop/assets/images/ellipse38.png
    - packages/eshop/assets/images/ellipse40.png
    - packages/eshop/assets/images/ellipse39.png
    - packages/eshop/assets/images/ellipse41.png
    - packages/eshop/assets/images/rectangle433.png
    - packages/eshop/assets/images/rectangle434.png
    - packages/eshop/assets/images/bookmark.svg
    - packages/eshop/assets/images/image14.png
    - packages/eshop/assets/images/tailorsdummy.svg
    - packages/eshop/assets/images/12.svg
    - packages/eshop/assets/images/rectangle440.png
    - packages/eshop/assets/images/rectangle441.png
    - packages/eshop/assets/images/4.svg
    - packages/eshop/assets/images/image3.png
    - packages/eshop/assets/images/chatmessage.svg
    - packages/eshop/assets/images/addmessage.svg
    - packages/eshop/assets/images/line26.svg
    - packages/eshop/assets/images/line27.svg
